<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Advanced_Ads_Gam_Ad_Type' => $baseDir . '/includes/class-advanced-ads-gam-ad-type.php',
    'Advanced_Ads_Gam_Admin' => $baseDir . '/admin/class-advanced-ads-gam-admin.php',
    'Advanced_Ads_Gam_Ajax' => $baseDir . '/admin/class-advanced-ads-gam-ajax.php',
    'Advanced_Ads_Gam_Api' => $baseDir . '/admin/interface-advanced-ads-gam-api.php',
    'Advanced_Ads_Gam_Api_Rest' => $baseDir . '/admin/class-advanced-ads-gam-api-rest.php',
    'Advanced_Ads_Gam_Api_Soap' => $baseDir . '/admin/class-advanced-ads-gam-api-soap.php',
    'Advanced_Ads_Gam_Importer' => $baseDir . '/admin/class-advanced-ads-gam-importer.php',
    'Advanced_Ads_Gam_Oauth2' => $baseDir . '/admin/class-advanced-ads-gam-oauth2.php',
    'Advanced_Ads_Network_Gam' => $baseDir . '/includes/class-advanced-ads-network-gam.php',

);
