<?php

// autoload_static.php @generated by Composer

namespace AdvancedAdsGam\Composer\Autoload;

class ComposerStaticInit_advanced_ads_gam
{
    public static $classMap = array (
        'Advanced_Ads_Gam_Ad_Type' => __DIR__ . '/../..' . '/includes/class-advanced-ads-gam-ad-type.php',
        'Advanced_Ads_Gam_Admin' => __DIR__ . '/../..' . '/admin/class-advanced-ads-gam-admin.php',
        'Advanced_Ads_Gam_Ajax' => __DIR__ . '/../..' . '/admin/class-advanced-ads-gam-ajax.php',
        'Advanced_Ads_Gam_Api' => __DIR__ . '/../..' . '/admin/interface-advanced-ads-gam-api.php',
        'Advanced_Ads_Gam_Api_Rest' => __DIR__ . '/../..' . '/admin/class-advanced-ads-gam-api-rest.php',
        'Advanced_Ads_Gam_Api_Soap' => __DIR__ . '/../..' . '/admin/class-advanced-ads-gam-api-soap.php',
        'Advanced_Ads_Gam_Importer' => __DIR__ . '/../..' . '/admin/class-advanced-ads-gam-importer.php',
        'Advanced_Ads_Gam_Oauth2' => __DIR__ . '/../..' . '/admin/class-advanced-ads-gam-oauth2.php',
        'Advanced_Ads_Network_Gam' => __DIR__ . '/../..' . '/includes/class-advanced-ads-network-gam.php',

    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInit_advanced_ads_gam::$classMap;

        }, null, ClassLoader::class);
    }
}
