<?php

$dir = realpath( __DIR__ . '/..' );

return array (
  'ACA\\YoastSeo\\Asset\\Script\\Admin' => $dir . '/classes/Asset/Script/Admin.php',
  'ACA\\YoastSeo\\Column\\Post\\FacebookDescription' => $dir . '/classes/Column/Post/FacebookDescription.php',
  'ACA\\YoastSeo\\Column\\Post\\FacebookImage' => $dir . '/classes/Column/Post/FacebookImage.php',
  'ACA\\YoastSeo\\Column\\Post\\FacebookTitle' => $dir . '/classes/Column/Post/FacebookTitle.php',
  'ACA\\YoastSeo\\Column\\Post\\FocusKW' => $dir . '/classes/Column/Post/FocusKW.php',
  'ACA\\YoastSeo\\Column\\Post\\FocusKeywordCount' => $dir . '/classes/Column/Post/FocusKeywordCount.php',
  'ACA\\YoastSeo\\Column\\Post\\IsIndexed' => $dir . '/classes/Column/Post/IsIndexed.php',
  'ACA\\YoastSeo\\Column\\Post\\Linked' => $dir . '/classes/Column/Post/Linked.php',
  'ACA\\YoastSeo\\Column\\Post\\Links' => $dir . '/classes/Column/Post/Links.php',
  'ACA\\YoastSeo\\Column\\Post\\MetaDesc' => $dir . '/classes/Column/Post/MetaDesc.php',
  'ACA\\YoastSeo\\Column\\Post\\PrimaryTaxonomy' => $dir . '/classes/Column/Post/PrimaryTaxonomy.php',
  'ACA\\YoastSeo\\Column\\Post\\Readability' => $dir . '/classes/Column/Post/Readability.php',
  'ACA\\YoastSeo\\Column\\Post\\Score' => $dir . '/classes/Column/Post/Score.php',
  'ACA\\YoastSeo\\Column\\Post\\Title' => $dir . '/classes/Column/Post/Title.php',
  'ACA\\YoastSeo\\Column\\Post\\TwitterDescription' => $dir . '/classes/Column/Post/TwitterDescription.php',
  'ACA\\YoastSeo\\Column\\Post\\TwitterImage' => $dir . '/classes/Column/Post/TwitterImage.php',
  'ACA\\YoastSeo\\Column\\Post\\TwitterTitle' => $dir . '/classes/Column/Post/TwitterTitle.php',
  'ACA\\YoastSeo\\Column\\Taxonomy\\CanonicalUrl' => $dir . '/classes/Column/Taxonomy/CanonicalUrl.php',
  'ACA\\YoastSeo\\Column\\Taxonomy\\FocusKeyword' => $dir . '/classes/Column/Taxonomy/FocusKeyword.php',
  'ACA\\YoastSeo\\Column\\Taxonomy\\IncludeInSitemap' => $dir . '/classes/Column/Taxonomy/IncludeInSitemap.php',
  'ACA\\YoastSeo\\Column\\Taxonomy\\MetaDesc' => $dir . '/classes/Column/Taxonomy/MetaDesc.php',
  'ACA\\YoastSeo\\Column\\Taxonomy\\MetaTitle' => $dir . '/classes/Column/Taxonomy/MetaTitle.php',
  'ACA\\YoastSeo\\Column\\Taxonomy\\NoIndex' => $dir . '/classes/Column/Taxonomy/NoIndex.php',
  'ACA\\YoastSeo\\Column\\TermMeta' => $dir . '/classes/Column/TermMeta.php',
  'ACA\\YoastSeo\\Column\\User\\AuthorPageMetaDesc' => $dir . '/classes/Column/User/AuthorPageMetaDesc.php',
  'ACA\\YoastSeo\\Column\\User\\AuthorPageTitle' => $dir . '/classes/Column/User/AuthorPageTitle.php',
  'ACA\\YoastSeo\\Column\\User\\DisableReadabilityAnalysis' => $dir . '/classes/Column/User/DisableReadabilityAnalysis.php',
  'ACA\\YoastSeo\\Column\\User\\DisableSeoAnalysis' => $dir . '/classes/Column/User/DisableSeoAnalysis.php',
  'ACA\\YoastSeo\\Column\\User\\NoIndexAuthor' => $dir . '/classes/Column/User/NoIndexAuthor.php',
  'ACA\\YoastSeo\\Dependencies' => $dir . '/classes/Dependencies.php',
  'ACA\\YoastSeo\\Editing\\Post\\IsIndexed' => $dir . '/classes/Editing/Post/IsIndexed.php',
  'ACA\\YoastSeo\\Editing\\Post\\PrimaryTaxonomy' => $dir . '/classes/Editing/Post/PrimaryTaxonomy.php',
  'ACA\\YoastSeo\\Editing\\Storage\\Post\\SocialImage' => $dir . '/classes/Editing/Storage/Post/SocialImage.php',
  'ACA\\YoastSeo\\Editing\\Taxonomy\\SeoMeta' => $dir . '/classes/Editing/Taxonomy/SeoMeta.php',
  'ACA\\YoastSeo\\Editing\\User\\ToggleOn' => $dir . '/classes/Editing/User/ToggleOn.php',
  'ACA\\YoastSeo\\Export\\Post\\Title' => $dir . '/classes/Export/Post/Title.php',
  'ACA\\YoastSeo\\Filtering\\Post\\PrimaryTaxonomy' => $dir . '/classes/Filtering/Post/PrimaryTaxonomy.php',
  'ACA\\YoastSeo\\Search\\Post\\IsIndexed' => $dir . '/classes/Search/Post/IsIndexed.php',
  'ACA\\YoastSeo\\Service\\Admin' => $dir . '/classes/Service/Admin.php',
  'ACA\\YoastSeo\\Service\\ColumnGroups' => $dir . '/classes/Service/ColumnGroups.php',
  'ACA\\YoastSeo\\Service\\Columns' => $dir . '/classes/Service/Columns.php',
  'ACA\\YoastSeo\\Service\\HideFilters' => $dir . '/classes/Service/HideFilters.php',
  'ACA\\YoastSeo\\Setting\\PrimaryTaxonomy' => $dir . '/classes/Setting/PrimaryTaxonomy.php',
  'ACA\\YoastSeo\\Settings\\ListScreen\\HideOnScreen\\FilterReadabilityScore' => $dir . '/classes/Settings/ListScreen/HideOnScreen/FilterReadabilityScore.php',
  'ACA\\YoastSeo\\Settings\\ListScreen\\HideOnScreen\\FilterSeoScores' => $dir . '/classes/Settings/ListScreen/HideOnScreen/FilterSeoScores.php',
  'ACA\\YoastSeo\\YoastSeo' => $dir . '/classes/YoastSeo.php',
);