<?php
function stm_get_layout_options($layout)
{
    $options = call_user_func('stm_theme_options_' . $layout);
    $options = json_decode($options, true);
    $options['show_page_title'] = 'false';
    return $options;
}

function stm_theme_options_default()
{
    $json = '{"primary_color":"rgba(255,31,89,1)",
	"main_bg":"rgba(245,245,245,1)",
	"max_width_content":"1140",
	"post_global_template":"default",
	"post_crop_image":"yes",
	"post_sidebar_id":"default",
	"post_sidebar_position":"right",
	"posts_view_type":"list",
	"body":"{\"color\":\"rgba(37,37,37,1)\",\"line-height\":\"25\",\"font-size\":\"15\",\"font-family\":\"Merriweather\",\"selectors\":\"body\"}",
	".menu":"{\"selectors\":\".nav-menu, .menu, .stm-navigation\",\"color\":\"rgba(39,48,68,1)\",\"font-family\":\"Merriweather\",\"font-size\":\"13\",\"line-height\":\"18\"}",
	".blockquote":"{\"selectors\":\"blockquote, .quote\"}",
	"default_header_font_family":"Merriweather",
	"default_header_font_color":"rgba(34,34,34,1)",
	"h1, .h1":"{\"color\":\"rgba(34,34,34,1)\",\"font-size\":\"49\",\"line-height\":\"55\"}",
	"h2, .h2":"",
	"h3, .h3":"",
	"h4, .h4":"",
	"h5, .h5":"",
	"h6, .h6":"{\"font-family\":\"\",\"color\":\"rgba(232,25,25,1)\",\"font-size\":\"16\",\"line-height\":\"\"}",
	"footer_main_bg":"rgba(39,48,68,1)",
	"copyright":"Copyright \u00a9 2018 ",
	"privacy_link":"http:\/\/rpivacy.com",
	"terms_link":"http:\/\/terms.com",
	"socials":"{\"facebook\":\"https:\/\/facebook.com\",\"twitter\":\"https:\/\/twitter.com\"}",
	"categ_head_bg_img":481,
	"categ_view_type":"grid",
	"tag_head_bg_img":481,
	"tag_view_type":"",
	"search_head_bg_img":481,
	"advert_banner":"",
	"advert_link":""}';

    return $json;
}

function stm_theme_options_demo_three()
{
    $json = '{"primary_color":"rgba(79,190,110,1)",
    "main_bg":"rgba(245,245,245,1)",
    "max_width_content":"1200",
    "post_global_template":"style_4",
    "post_crop_image":"yes",
    "post_sidebar_id":"",
    "post_sidebar_position":"no_sidebar",
    "posts_view_type":"list",
    "body":"{\"color\":\"\",\"line-height\":\"26\",\"font-size\":\"15\",\"font-family\":\"Rubik\",\"selectors\":\"body, .normal-font\"}",
    ".menu":"{\"selectors\":\".nav-menu, .menu, .stm-navigation\",\"color\":\"\",\"font-family\":\"Rubik\",\"font-size\":\"\",\"line-height\":\"\"}",
    ".blockquote":"{\"selectors\":\"blockquote, .quote\",\"font-family\":\"Open Sans\",\"font-size\":\"24\",\"line-height\":\"36\"}",
    "default_header_font_family":"Ubuntu",
    "default_header_font_color":"rgba(34,34,34,1)",
    "h1, .h1":"{\"color\":\"rgba(34,34,34,1)\",\"font-size\":\"60\",\"line-height\":\"72\"}",
    "h2, .h2":"{\"font-size\":\"40\",\"line-height\":\"52\"}",
    "h3, .h3":"{\"font-size\":\"30\",\"line-height\":\"36\"}",
    "h4, .h4":"{\"font-size\":\"22\",\"line-height\":\"36\"}",
    "h5, .h5":"{\"font-size\":\"16\",\"line-height\":\"24\"}",
    "h6, .h6":"{\"font-family\":\"Rubik\",\"color\":\"\",\"font-size\":\"16\",\"line-height\":\"24\"}",
    "footer_main_bg":"#222a22",
    "footer_bg_img":238,
    "copyright":"Copyright \u00a9 2018 ",
    "privacy_link":"",
    "terms_link":"",
    "socials":"{\"facebook\":\"https:\/\/facebook.com\",\"twitter\":\"https:\/\/twitter.com\"}",
    "404_content_bg_img":251,
    "categ_head_bg_img":"",
    "categ_view_type":"grid",
    "tag_head_bg_img":"",
    "tag_view_type":"",
    "search_head_bg_img":"",
    "advert_banner":"",
    "advert_link":""}';

    return $json;
}

function stm_theme_options_demo_two()
{
    $json = '{"primary_color":"rgba(238,116,35,1)",
    "main_bg":"rgba(245,245,245,1)",
    "max_width_content":"1200",
    "post_global_template":"style_3",
    "post_crop_image":"yes",
    "post_sidebar_id":"",
    "post_sidebar_position":"no_sidebar",
    "posts_view_type":"grid",
    "body":"{\"color\":\"\",\"line-height\":\"26\",\"font-size\":\"15\",\"font-family\":\"Rubik\",\"selectors\":\"body, .normal-font\"}",
    ".menu":"{\"selectors\":\".nav-menu, .menu, .stm-navigation\",\"color\":\"\",\"font-family\":\"Rubik\",\"font-size\":\"\",\"line-height\":\"\"}",
    ".blockquote":"{\"selectors\":\"blockquote, .quote\",\"font-family\":\"Open Sans\",\"font-size\":\"24\",\"line-height\":\"36\"}",
    "default_header_font_family":"Open Sans",
    "default_header_font_color":"rgba(34,34,34,1)",
    "h1, .h1":"{\"color\":\"rgba(34,34,34,1)\",\"font-size\":\"60\",\"line-height\":\"72\"}",
    "h2, .h2":"{\"font-size\":\"40\",\"line-height\":\"52\"}",
    "h3, .h3":"{\"font-size\":\"30\",\"line-height\":\"36\"}",
    "h4, .h4":"{\"font-size\":\"22\",\"line-height\":\"36\"}",
    "h5, .h5":"{\"font-size\":\"16\",\"line-height\":\"24\"}",
    "h6, .h6":"{\"font-family\":\"Rubik\",\"color\":\"\",\"font-size\":\"16\",\"line-height\":\"24\"}",
    "footer_main_bg":"#1c1c1c",
    "footer_bg_img":238,"copyright":"Copyright \u00a9 2018 ",
    "privacy_link":"",
    "terms_link":"",
    "socials":"{\"facebook\":\"https:\/\/facebook.com\",\"twitter\":\"https:\/\/twitter.com\"}",
    "404_content_bg_img":251,"categ_head_bg_img":"",
    "categ_view_type":"grid",
    "tag_head_bg_img":"",
    "tag_view_type":"",
    "search_head_bg_img":"",
    "advert_banner":"",
    "advert_link":""}';

    return $json;
}

function stm_theme_options_beauty() {
    $json = '{
    "primary_color":"rgba(254,32,89,1)",
    "main_bg":"rgba(253,242,240,1)",
    "max_width_content":"1200",
    "stmt_post_head_bg":"rgba(253,242,240,1)",
    "boxed_layout":"",
    "boxed_layout_bg":"",
    "home_sticky_sidebar":false,
    "post_global_template":"style_4",
    "post_crop_image":"yes",
    "post_sidebar_id":"",
    "post_sidebar_position":"no_sidebar",
    "posts_view_type":"grid",
    "body":"{\"color\":\"rgba(34,34,34,1)\",\"line-height\":\"30\",\"font-size\":\"15\",\"font-family\":\"Josefin Sans\",\"selectors\":\"body, .normal-font\",\"font-weight\":\"400\"}",
    ".menu":"{\"selectors\":\".nav-menu, .menu, .stm-navigation\",\"color\":\"rgba(255,255,255,1)\",\"font-family\":\"Roboto Slab\",\"font-size\":\"13\",\"line-height\":\"18\",\"font-weight\":\"\"}",
    ".blockquote":"{\"selectors\":\"blockquote, .quote\",\"font-family\":\"Open Sans\",\"font-size\":\"24\",\"line-height\":\"36\"}",
    "default_header_font_family":"Roboto Slab",
    "default_header_font_color":"rgba(34,34,34,1)",
    "h1, .h1":"{\"color\":\"rgba(0,0,0,1)\",\"font-size\":\"36\",\"line-height\":\"60\",\"font-family\":\"Roboto Slab\",\"font-weight\":\"300\",\"letter-spacing\":\"1.2\"}",
    "h2, .h2":"{\"font-size\":\"36\",\"line-height\":\"52\",\"font-family\":\"Roboto Slab\",\"color\":\"rgba(0,0,0,1)\",\"font-weight\":\"300\",\"letter-spacing\":\"1.2\"}",
    "h3, .h3":"{\"font-size\":\"36\",\"line-height\":\"50\",\"font-family\":\"Roboto Slab\",\"color\":\"rgba(0,0,0,1)\",\"font-weight\":\"300\",\"letter-spacing\":\"0.9\",\"selectors\":\"h3, .heading-title\"}",
    "h4, .h4":"{\"font-size\":\"22\",\"line-height\":\"36\"}",
    "h5, .h5":"{\"font-size\":\"16\",\"line-height\":\"24\"}",
    "h6, .h6":"{\"font-family\":\"Roboto Slab\",\"color\":\"\",\"font-size\":\"16\",\"line-height\":\"24\"}",
    "enable_crypto_ticker":"",
    "cryptos_api_key":"",
    "cryptos":"",
    "scroll_top":"",
    "footer_top_bg":"",
    "footer_main_bg":"rgb(250, 241, 240)",
    "footer_bg_img":238,"copyright":"Copyright \u00a9 2018. Gutenmag WordPress Theme by StylemixThemes <\/a>",
    "privacy_link":"",
    "terms_link":"",
    "socials":"{\"facebook\":\"facebook.com\",\"twitter\":\"twitter.com\",\"youtube\":\"youtube.com\",\"instagram\":\"instagram.com\"}",
    "404_content_bg_img":251,"categ_head_bg_img":"",
    "categ_view_type":"grid",
    "tag_head_bg_img":"",
    "tag_view_type":"",
    "search_head_bg_img":"",
    "advert_banner":"",
    "advert_link":"",
    "mc_api_key":"",
    "mc_list_id":""}';

    return $json;
}

function stm_theme_options_cryptomag()
{
    $json = '{
		"primary_color": "#ecb32a",
		"main_bg": "rgba(245,245,245,1)",
		"max_width_content": "1200",
		"boxed_layout": true,
		"boxed_layout_bg": 475,
		"home_sticky_sidebar": true,
		"post_global_template": "style_3",
		"post_crop_image": "yes",
		"post_sidebar_id": "",
		"post_sidebar_position": "no_sidebar",
		"posts_view_type": "grid",
		"body": "{\"color\":\"rgba(34,34,34,1)\",\"line-height\":\"26\",\"font-size\":\"15\",\"font-family\":\"Rubik\",\"selectors\":\"body, .normal-font\"}",
		".menu": "{\"selectors\":\"body .stm-navigation.stm-navigation__default ul li a\",\"color\":\"rgba(255,255,255,1)\",\"font-family\":\"Rubik\",\"font-size\":\"13\",\"line-height\":\"24\",\"font-weight\":\"500\",\"letter-spacing\":\"0.5px\"}",
		".blockquote": "{\"selectors\":\"blockquote, .quote\",\"font-family\":\"Open Sans\",\"font-size\":\"24\",\"line-height\":\"36\"}",
		"default_header_font_family": "Ubuntu",
		"default_header_font_color": "rgba(34,34,34,1)",
		"h1, .h1": "{\"color\":\"rgba(34,34,34,1)\",\"font-size\":\"60\",\"line-height\":\"72\"}",
		"h2, .h2": "{\"font-size\":\"40\",\"line-height\":\"52\"}",
		"h3, .h3": "{\"font-size\":\"30\",\"line-height\":\"36\"}",
		"h4, .h4": "{\"font-size\":\"22\",\"line-height\":\"36\"}",
		"h5, .h5": "{\"font-size\":\"16\",\"line-height\":\"24\"}",
		"h6, .h6": "{\"font-family\":\"Rubik\",\"color\":\"\",\"font-size\":\"16\",\"line-height\":\"24\"}",
		"enable_crypto_ticker": true,
		"cryptos_api_key": "",
		"cryptos": "[{\"name\":\"Bitcoin\",\"value\":\"bitcoin\"},{\"name\":\"Cardano\",\"value\":\"cardano\"},{\"name\":\"Ethereum Classic\",\"value\":\"ethereum-classic\"},{\"name\":\"Wanchain\",\"value\":\"wanchain\"},{\"name\":\"Loopring [NEO]\",\"value\":\"loopring-neo\"},{\"name\":\"Horizen\",\"value\":\"zencash\"},{\"name\":\"Bitcoin Cash\",\"value\":\"bitcoin-cash\"},{\"name\":\"NEM\",\"value\":\"nem\"},{\"name\":\"Raiden Network Token\",\"value\":\"raiden-network-token\"},{\"name\":\"Ethereum\",\"value\":\"ethereum\"}]",
		"scroll_top": true,
		"scroll_arrow_position": "pos_1",
		"footer_main_bg": "#222a22",
		"footer_bg_img": "",
		"copyright": "Copyright \u00a9 2018 ",
		"privacy_link": "",
		"terms_link": "",
		"socials": "{\"facebook\":\"facebook.com\",\"instagram\":\"instagram.com\",\"twitter\":\"twitter.com\",\"linkedin\":\"linkedin.com\"}",
		"404_content_bg_img": "",
		"categ_head_bg_img": "",
		"categ_view_type": "grid",
		"tag_head_bg_img": "",
		"tag_view_type": "",
		"search_head_bg_img": "",
		"advert_banner": "",
		"advert_link": "",
		"mc_api_key": "",
		"mc_list_id": ""
	}';

    return $json;
}

function stm_theme_options_car_magazine()
{
    $json = '{
          "primary_color": "#73ea94",
          "main_bg": "rgba(255,255,255,1)",
          "max_width_content": "1200",
          "stmt_post_head_bg": "rgba(255,255,255,1)",
          "boxed_layout": "",
          "boxed_layout_bg": "",
          "home_sticky_sidebar": true,
          "post_global_template": "style_4",
          "post_crop_image": "yes",
          "post_sidebar_id": "",
          "post_sidebar_position": "no_sidebar",
          "posts_view_type": "grid",
          "body": "{\"color\":\"\",\"line-height\":\"26\",\"font-size\":\"15\",\"font-family\":\"Open Sans\",\"selectors\":\"body, .normal-font\"}",
          ".menu": "{\"selectors\":\".nav-menu, .menu, .stm-navigation, body .stm-navigation.stm-navigation__default > ul > li > a\",\"color\":\"rgba(255,255,255,1)\",\"font-family\":\"Montserrat\",\"font-size\":\"13\",\"line-height\":\"18\",\"font-weight\":\"700\"}",
          ".blockquote": "{\"selectors\":\"blockquote, .quote\",\"font-family\":\"Open Sans\",\"font-size\":\"24\",\"line-height\":\"36\"}",
          "default_header_font_family": "Montserrat",
          "default_header_font_color": "rgba(34,34,34,1)",
          "h1, .h1": "{\"color\":\"rgba(34,34,34,1)\",\"font-size\":\"54\",\"line-height\":\"60\"}",
          "h2, .h2": "{\"font-size\":\"40\",\"line-height\":\"52\"}",
          "h3, .h3": "{\"font-size\":\"30\",\"line-height\":\"36\"}",
          "h4, .h4": "{\"font-size\":\"24\",\"line-height\":\"36\",\"font-weight\":\"700\"}",
          "h5, .h5": "{\"font-size\":\"16\",\"line-height\":\"24\"}",
          "h6, .h6": "{\"font-family\":\"\",\"color\":\"\",\"font-size\":\"14\",\"line-height\":\"18\",\"font-weight\":\"700\"}",
          "enable_crypto_ticker": "",
          "cryptos_api_key": "",
          "cryptos": "",
          "scroll_top": "",
          "footer_top_bg": "rgba(39,48,68,1)",
          "footer_main_bg": "rgba(39,48,68,1)",
          "footer_bg_img": 238,
          "copyright": "Copyright \u00a9 2018 ",
          "privacy_link": "",
          "terms_link": "",
          "socials": "{\"facebook\":\"https:\/\/facebook.com\",\"twitter\":\"https:\/\/twitter.com\",\"instagram\":\"https:\/\/instagram.com\",\"pinterest\":\"https:\/\/pinterest.com\"}",
          "404_content_bg_img": 251,
          "categ_head_bg_img": "",
          "categ_view_type": "grid",
          "tag_head_bg_img": "",
          "tag_view_type": "",
          "search_head_bg_img": "",
          "advert_banner": "",
          "advert_link": "",
          "mc_api_key": "asdsadasd",
          "mc_list_id": "dsadasd"
        }';

    return $json;
}

function stm_theme_options_personal()
{
    $json = '{
    "primary_color":"#b79e80",
    "main_bg":"rgba(255,255,255,1)",
    "max_width_content":"1200",
    "stmt_post_head_bg":"rgba(255,255,255,1)",
    "boxed_layout":"",
    "boxed_layout_bg":"",
    "home_sticky_sidebar":"",
    "post_global_template":"style_4",
    "post_crop_image":"yes",
    "post_sidebar_id":"",
    "post_sidebar_position":"no_sidebar",
    "posts_view_type":"list",
    "body":"{\"color\":\"\",\"line-height\":\"24\",\"font-size\":\"13\",\"font-family\":\"Poppins\",\"selectors\":\"body, .normal-font\",\"font-weight\":\"400\"}",
    ".menu":"{\"selectors\":\".nav-menu, .menu, .stm-navigation\",\"color\":\"\",\"font-family\":\"Poppins\",\"font-size\":\"\",\"line-height\":\"\",\"font-weight\":\"400\"}",
    ".blockquote":"{\"selectors\":\"blockquote, .quote\",\"font-family\":\"Poppins\",\"font-size\":\"24\",\"line-height\":\"36\"}",
    "default_header_font_family":"Lora",
    "default_header_font_color":"rgba(34,34,34,1)",
    "h1, .h1":"{\"color\":\"rgba(34,34,34,1)\",\"font-size\":\"48\",\"line-height\":\"60\"}",
    "h2, .h2":"{\"font-size\":\"42\",\"line-height\":\"54\"}",
    "h3, .h3":"{\"font-size\":\"36\",\"line-height\":\"48\",\"selectors\":\".comment-reply-title, .has-drop-cap:first-letter\",\"font-family\":\"Lora\"}",
    "h4, .h4":"{\"font-size\":\"30\",\"line-height\":\"42\",\"selectors\":\".comments-title.text-transform\",\"font-family\":\"Lora\"}",
    "h5, .h5":"{\"font-size\":\"24\",\"line-height\":\"36\",\"font-family\":\"Lora\"}",
    "h6, .h6":"{\"font-family\":\"Poppins\",\"color\":\"\",\"font-size\":\"18\",\"line-height\":\"30\"}",
    "scroll_top":true,
    "scroll_arrow_position":"pos_2",
    "footer_top_bg":"",
    "footer_main_bg":"#222a22",
    "footer_logo":446,
    "footer_bg_img":238,
    "copyright":"\u00a9 2018 Gutenmag by StylemixThemes. All rights reserved",
    "privacy_link":"",
    "terms_link":"",
    "socials":"{\"facebook\":\"https:\/\/facebook.com\",\"twitter\":\"https:\/\/twitter.com\",\"instagram\":\"https:\/\/instagram.com\",\"youtube\":\"https:\/\/youtube.com\"}",
    "404_content_bg_img":251,
    "categ_head_bg_img":"",
    "categ_view_type":"grid",
    "tag_head_bg_img":"",
    "tag_view_type":"",
    "search_head_bg_img":"",
    "advert_banner":"",
    "advert_link":"",
    "mc_api_key":"1111",
    "mc_list_id":"2222"}';

    return $json;
}