<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite8e0a5a71466971c09bf3d823d560b97
{
    public static $classMap = array (
        'AdvancedAds\\StickyAds\\Admin\\Metabox' => __DIR__ . '/../..' . '/includes/admin/class-metabox.php',
        'AdvancedAds\\StickyAds\\Admin\\Placement_Settings' => __DIR__ . '/../..' . '/includes/admin/class-placement-settings.php',
        'AdvancedAds\\StickyAds\\Admin\\Settings' => __DIR__ . '/../..' . '/includes/admin/class-settings.php',
        'AdvancedAds\\StickyAds\\Autoloader' => __DIR__ . '/../..' . '/includes/class-autoloader.php',
        'AdvancedAds\\StickyAds\\Bootstrap' => __DIR__ . '/../..' . '/includes/class-bootstrap.php',
        'AdvancedAds\\StickyAds\\Frontend' => __DIR__ . '/../..' . '/includes/class-frontend.php',
        'AdvancedAds\\StickyAds\\Placement_Types' => __DIR__ . '/../..' . '/includes/class-placement-types.php',
        'AdvancedAds\\StickyAds\\Plugin' => __DIR__ . '/../..' . '/includes/class-plugin.php',
        'AdvancedAds\\StickyAds\\Types\\Sticky_Footer' => __DIR__ . '/../..' . '/includes/types/class-sticky-footer.php',
        'AdvancedAds\\StickyAds\\Types\\Sticky_Header' => __DIR__ . '/../..' . '/includes/types/class-sticky-header.php',
        'AdvancedAds\\StickyAds\\Types\\Sticky_Left_Sidebar' => __DIR__ . '/../..' . '/includes/types/class-sticky-left-sidebar.php',
        'AdvancedAds\\StickyAds\\Types\\Sticky_Left_Window' => __DIR__ . '/../..' . '/includes/types/class-sticky-left-window.php',
        'AdvancedAds\\StickyAds\\Types\\Sticky_Right_Sidebar' => __DIR__ . '/../..' . '/includes/types/class-sticky-right-sidebar.php',
        'AdvancedAds\\StickyAds\\Types\\Sticky_Right_Window' => __DIR__ . '/../..' . '/includes/types/class-sticky-right-window.php',
        'AdvancedAds\\StickyAds\\Wrappers' => __DIR__ . '/../..' . '/includes/class-wrappers.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInite8e0a5a71466971c09bf3d823d560b97::$classMap;

        }, null, ClassLoader::class);
    }
}
