<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'AdvancedAds\\StickyAds\\Admin\\Metabox' => $baseDir . '/includes/admin/class-metabox.php',
    'AdvancedAds\\StickyAds\\Admin\\Placement_Settings' => $baseDir . '/includes/admin/class-placement-settings.php',
    'AdvancedAds\\StickyAds\\Admin\\Settings' => $baseDir . '/includes/admin/class-settings.php',
    'AdvancedAds\\StickyAds\\Autoloader' => $baseDir . '/includes/class-autoloader.php',
    'AdvancedAds\\StickyAds\\Bootstrap' => $baseDir . '/includes/class-bootstrap.php',
    'AdvancedAds\\StickyAds\\Frontend' => $baseDir . '/includes/class-frontend.php',
    'AdvancedAds\\StickyAds\\Placement_Types' => $baseDir . '/includes/class-placement-types.php',
    'AdvancedAds\\StickyAds\\Plugin' => $baseDir . '/includes/class-plugin.php',
    'AdvancedAds\\StickyAds\\Types\\Sticky_Footer' => $baseDir . '/includes/types/class-sticky-footer.php',
    'AdvancedAds\\StickyAds\\Types\\Sticky_Header' => $baseDir . '/includes/types/class-sticky-header.php',
    'AdvancedAds\\StickyAds\\Types\\Sticky_Left_Sidebar' => $baseDir . '/includes/types/class-sticky-left-sidebar.php',
    'AdvancedAds\\StickyAds\\Types\\Sticky_Left_Window' => $baseDir . '/includes/types/class-sticky-left-window.php',
    'AdvancedAds\\StickyAds\\Types\\Sticky_Right_Sidebar' => $baseDir . '/includes/types/class-sticky-right-sidebar.php',
    'AdvancedAds\\StickyAds\\Types\\Sticky_Right_Window' => $baseDir . '/includes/types/class-sticky-right-window.php',
    'AdvancedAds\\StickyAds\\Wrappers' => $baseDir . '/includes/class-wrappers.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
);
